### ISSUE TITLE
Cargo panic when running web build

### ISSUE THREAD

**Issue by ewpratten** [koute/cargo-web#250]
When running `cargo web build`, I get the following output:

```
Downloading emscripten-1.38.19-1-x86_64-unknown-linux-gnu.tgz...
201.71 MB / 201.71 MB [========================================================] 100.00 % 4.92 MB/s 
thread 'main' panicked at 'attempted to leave type `digest::generic_array::GenericArray<std::string::String, digest::generic_array::typenum::UInt<digest::generic_array::typenum::UInt<digest::generic_array::typenum::UInt<digest::generic_array::typenum::UInt<digest::generic_array::typenum::UInt<digest::generic_array::typenum::UInt<digest::generic_array::typenum::UTerm, digest::generic_array::typenum::B1>, digest::generic_array::typenum::B0>, digest::generic_array::typenum::B0>, digest::generic_array::typenum::B0>, digest::generic_array::typenum::B0>, digest::generic_array::typenum::B0>>` uninitialized, which is invalid', /home/ewpratten/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:671:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Backtrace output:

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:50:5
   3: cargo_web::package::download_package
   4: cargo_web::emscripten::initialize_emscripten
   5: cargo_web::build::Project::build_or_check
   6: cargo_web::cmd_start::LastBuild::new
   7: cargo_web::cmd_start::command_start
   8: cargo_web::run
   9: cargo_web::main
```

**Comment by ewpratten** [comment]
This only happens with the `wasm32-unknown-emscripten` target

**Comment by creikey** [comment]
I have this same issue on ubuntu

**Comment by ewpratten** [comment]
@creikey Ya, I'm on Ubuntu 20.04 LTS as well

**Comment by gabrielpacheco23** [comment]
Same here

**Comment by zdimension** [comment]
Getting this too on WSL Ubuntu 21.10, rustc 1.58.1 (db9d1b20b)

**Comment by daniel-brenot** [comment]
Any update on this? I also can't get this to build.
