### ISSUE TITLE
Cash on cargo web build in WSL

### ISSUE THREAD

**Issue by JFrandon** [koute/cargo-web#255]
Hi I am running `cargo web build` in a project including stdweb an I am running into the following panic:

```    Processing "RustStart.wasm"...
thread 'main' panicked at 'unknown name section chunk type: 7', /home/jfrandon/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-web-0.6.26/src/wasm_context.rs:642:41
stack backtrace:
   0:     0x7f55c13af470 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f55c13af470 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f55c13af470 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f55c13af470 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f55c13d33af - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x7f55c13a6f42 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x7f55c13b1bb5 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f55c13b1bb5 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f55c13b1bb5 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x7f55c13b1663 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x7f55c13b21bd - std::panicking::rust_panic_with_hook::hb89f5f19036e6af8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:     0x7f55c13b1d57 - std::panicking::begin_panic_handler::{{closure}}::h119e7951427f41da
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:497:13
  12:     0x7f55c13af92c - std::sys_common::backtrace::__rust_end_short_backtrace::hce386c44bf47a128
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x7f55c13b1cb9 - rust_begin_unwind
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  14:     0x7f55c0d60f3b - std::panicking::begin_panic_fmt::h400b8e9dca200408
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:435:5
  15:     0x7f55c0ef27ad - cargo_web::wasm_context::Context::from_module::h6b26812d36925aaf
  16:     0x7f55c0e43412 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h2148908ec7c8b951
  17:     0x7f55c0e04321 - cargo_web::cargo_shim::BuildConfig::build_internal::h4e59aba7c9c6ad92
  18:     0x7f55c0e019e1 - cargo_web::cargo_shim::BuildConfig::build::h576542e0e83069ff
  19:     0x7f55c0e60595 - cargo_web::build::Project::build_or_check::h496e70f51c760ecc
  20:     0x7f55c0e242dc - cargo_web::cmd_build::command_build_or_check::hce738310be10778b
  21:     0x7f55c0d919c5 - cargo_web::run::h92650884409e99c2
  22:     0x7f55c0d6c347 - cargo_web::main::h75072d8634afa7b5
  23:     0x7f55c0d72db3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5b1d37564ed1c367
  24:     0x7f55c0d72dc9 - std::rt::lang_start::{{closure}}::h4fd5779e81b95fee
  25:     0x7f55c13b26ba - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h44574effd2120c86
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:259:13
  26:     0x7f55c13b26ba - std::panicking::try::do_call::h10b0bd4879c8dfb0
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:379:40
  27:     0x7f55c13b26ba - std::panicking::try::h60c6780d33419e92
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:343:19
  28:     0x7f55c13b26ba - std::panic::catch_unwind::h111f33e08c52e2ce
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:431:14
  29:     0x7f55c13b26ba - std::rt::lang_start_internal::h126f2e09345dbfda
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/rt.rs:51:25
  30:     0x7f55c0d6c4d2 - main
  31:     0x7f55c087409b - __libc_start_main
  32:     0x7f55c0d620ca - _start
  33:                0x0 - <unknown>
```

Any Idea of what might be happening?

**Comment by renatocassino** [comment]
Same problem here :/

```
cargo web start               
warning: unused manifest key: cargo-web
warning: unused manifest key: default-target
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
    Processing "stdweb_example.wasm"...
thread 'main' panicked at 'unknown name section chunk type: 7', /home/<user>/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-web-0.6.26/src/wasm_context.rs:642:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I have no idea how to solve this

**Comment by JFrandon** [comment]
Welp I gave up on this issue
