### ISSUE TITLE
--target-webasm-emscripten --use-system-emscripten panics

### ISSUE THREAD

**Issue by svenstaro** [koute/cargo-web#29]
I get this:

```
RUST_BACKTRACE=1 cargo web start --target-webasm-emscripten --use-system-emscripten
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /checkout/src/libcore/result.rs:916:4
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
  10: cargo_web::command_start
  11: cargo_web::main
  12: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  13: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/rt.rs:58
  14: __libc_start_main
  15: _start
```

but `cargo web start --target-asmjs-emscripten --use-system-emscripten` works just fine. My system has emscripten 1.37.25 and binaryen 40 installed.

On top of fixing this error, I'd like to note that you should probably rather use an `expect` there instead of an `unwrap` so that people know what's wrong exactly.

**Comment by koute** [comment]
I've just updated my Arch system, installed Emscripten 1.37.25 and the newest Binaryen from AUR, deleted everything Emscripten related from my home directory, and... it looks like it works for me. Could you provide any other details as to how I could reproduce it?

And, yes, you're right that I should probably use `expect`s instead of `unwrap`s.

**Comment by svenstaro** [comment]
```
rustup toolchain list  # nightly-2017-12-20-x86_64-unknown-linux-gnu (default)
rustup component list  # ... rust-std-wasm32-unknown-emscripten (installed) ...
pacman -Q emscripten  # emscripten 1.37.25-1
pacman -Q binaryen  # binaryen 40-1
rm -rf target
rm -rf ~/.cargo/{git,registry}
rm -rf ~/.emscripten*
cargo install --force cargo-web
cargo web start --target-webasm-emscripten --use-system-emscripten
```
Same issue. strace of failure is attached: [failure.log](https://github.com/koute/cargo-web/files/1592921/failure.log)

Just running `cargo web build --target-webasm-emscripten --use-system-emscripten` doesn't have any apparent issues, by the way.

Strace of success when running `cargo web start --target-asmjs-emscripten --use-system-emscripten` is also attached: [success.log](https://github.com/koute/cargo-web/files/1592925/success.log)

Tree of my `target/`:

```
target
├── asmjs-unknown-emscripten
│   └── debug
│       ├── build
│       ├── deps
│       │   ├── libchrono-2fd615229cc521d6.rlib
│       │   ├── libdtoa-a564a532262db20e.rlib
│       │   ├── libitoa-990cf22ba2ea9c3f.rlib
│       │   ├── liblibc-7c4394f59a7e6328.rlib
│       │   ├── libnum-b4843d910b4352b3.rlib
│       │   ├── libnum_integer-92c39c5e0411968e.rlib
│       │   ├── libnum_iter-b115c1647297f67d.rlib
│       │   ├── libnum_traits-397dbe6347ef89c2.rlib
│       │   ├── libserde-b7d82c7ca1ee84cb.rlib
│       │   ├── libserde_json-47a616da4a72f5f4.rlib
│       │   ├── libstdweb-db0f91d68fd859f2.rlib
│       │   ├── libtime-dc457536a30c317c.rlib
│       │   ├── libyew-5a024746ea264d3c.rlib
│       │   ├── rust_web_experiments-8ad723d4edf085d8.js
│       │   └── rust_web_experiments-8ad723d4edf085d8.js.map
│       ├── examples
│       ├── incremental
│       ├── native
│       ├── rust-web-experiments.d
│       └── rust-web-experiments.js
├── debug
│   ├── build
│   ├── deps
│   ├── examples
│   ├── incremental
│   └── native
├── release
│   ├── build
│   ├── deps
│   ├── examples
│   ├── incremental
│   └── native
└── wasm32-unknown-emscripten
    ├── debug
    │   ├── build
    │   ├── deps
    │   │   ├── libchrono-2fd615229cc521d6.rlib
    │   │   ├── libdtoa-a564a532262db20e.rlib
    │   │   ├── libitoa-990cf22ba2ea9c3f.rlib
    │   │   ├── liblibc-7c4394f59a7e6328.rlib
    │   │   ├── libnum-b4843d910b4352b3.rlib
    │   │   ├── libnum_integer-92c39c5e0411968e.rlib
    │   │   ├── libnum_iter-b115c1647297f67d.rlib
    │   │   ├── libnum_traits-397dbe6347ef89c2.rlib
    │   │   ├── libserde-b7d82c7ca1ee84cb.rlib
    │   │   ├── libserde_json-47a616da4a72f5f4.rlib
    │   │   ├── libstdweb-db0f91d68fd859f2.rlib
    │   │   ├── libtime-dc457536a30c317c.rlib
    │   │   ├── libyew-5a024746ea264d3c.rlib
    │   │   ├── rust-web-experiments.js
    │   │   ├── rust_web_experiments.wasm
    │   │   ├── rust_web_experiments.wasm.map
    │   │   └── rust_web_experiments.wast
    │   ├── examples
    │   ├── incremental
    │   ├── native
    │   ├── rust_web_experiments.d
    │   ├── rust-web-experiments.d
    │   ├── rust-web-experiments.js
    │   └── rust_web_experiments.wasm
    └── release
        ├── build
        ├── deps
        │   ├── libchrono-660b00ca14c9780d.rlib
        │   ├── libdtoa-8391ea7de6ed0983.rlib
        │   ├── libitoa-5ce887a455bb08bc.rlib
        │   ├── liblibc-068fc36dc0a4b5be.rlib
        │   ├── libnum-beb00bba922b6f26.rlib
        │   ├── libnum_integer-ec8ffdc01cada393.rlib
        │   ├── libnum_iter-ab7ad761548eeb4d.rlib
        │   ├── libnum_traits-db1df3ab1a0fd3c2.rlib
        │   ├── libserde-b3732f73697f42bf.rlib
        │   ├── libserde_json-9eede9730ddc2803.rlib
        │   ├── libstdweb-8702dc47aa7774ce.rlib
        │   ├── libtime-b5f798a4b1233393.rlib
        │   ├── libyew-8fb319767385764b.rlib
        │   ├── rust-web-experiments.js
        │   └── rust_web_experiments.wasm
        ├── examples
        ├── incremental
        ├── native
        ├── rust_web_experiments.d
        ├── rust-web-experiments.d
        ├── rust-web-experiments.js
        └── rust_web_experiments.wasm

32 directories, 57 files
```

**Comment by svenstaro** [comment]
Looked into it again and found something I missed earlier: `rust-web-experiments.js` vs `rust_web_experiments.wasm`. So the wasm version is generated with underscores instead of dashes.

**Comment by svenstaro** [comment]
Doesn't seem to be a problem of cargo-web but cargo. I'll take a stab at finding out where that is exactly. I'll leave this issue open for now if you don't mind.

**Comment by svenstaro** [comment]
Ok found the code here: https://github.com/rust-lang/cargo/blob/e10c651ea142f0a8c077bc717462b2ea233e7e1c/src/cargo/ops/cargo_rustc/context.rs#L703

The comment seems to indicate that this is a bug of cargo-web after all which should also account for this behavior in cargo.

**Comment by koute** [comment]
Thanks for tracing it down!

It should be fixed on `master`.

**Comment by svenstaro** [comment]
Working nicely!
