### ISSUE TITLE
Panicked if build as a member of Cargo workspace

### ISSUE THREAD

**Issue by karuna** [koute/cargo-web#57]
I have a project with workspace, one of the workspace member is using cargo-web.
Outside the workspace it works fine, but if it's inside workspace member it's panicking. Both asmjs and wasm32 is panicking.

```
[workspace]
members = [
  "server/",
  "client/"
]
```

```
RUST_BACKTRACE=1 cargo web start --target wasm32-unknown-emscripten
thread 'main' panicked at 'Unknown target kind: 'dylib'', src/cargo_shim/mod.rs:236:38
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: <core::iter::FilterMap<I, F> as core::iter::iterator::Iterator>::next
   8: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
   9: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
  10: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  11: cargo_web::cargo_shim::CargoProject::new
  12: cargo_web::build::BuildArgs::load_project
  13: cargo_web::cmd_start::command_start
  14: cargo_web::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  17: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  18: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  19: main
  20: __libc_start_main
  21: _start
```

**Comment by koute** [comment]
Fixed on `master`; thanks for the report!

**Comment by kcking** [comment]
Hi @koute, thanks for the quick fix on this. The same happens for the `staticlib` crate-type as well. Is the fix the same as for `dylib`?

**Comment by karuna** [comment]
@koute thanks for the quick fix.

**Comment by karuna** [comment]
@koute I have confirmed it's working, do you want me to close this, or let this open for @kcking bug report as well?

**Comment by koute** [comment]
@karuna @kcking Sorry for the late reply, and thanks for your involvement here! Since this is fixed now - closing!
