### ISSUE TITLE
cargo web fails to compile/run after nightly toolchain update : unsupported custom section: 'linking'

### ISSUE THREAD

**Issue by jice-nospam** [koute/cargo-web#77]
cargo web ran fine so far with my project. But after a ` rustup update` this morning, I've got this error :

```
$ RUST_BACKTRACE=1 cargo web start --release
    Finished release [optimized] target(s) in 0.0 secs
    Garbage collecting "viper.wasm"...
    Processing "viper.wasm"...
thread 'main' panicked at 'unsupported custom section: 'linking'', src/wasm_context.rs:631:25
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:206
   3: std::panicking::default_hook
             at libstd/panicking.rs:222
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:400
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:347
   6: cargo_web::wasm_context::Context::from_module
   7: cargo_web::wasm::process_wasm_file
   8: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &'a mut F>::call_mut
  9: cargo_web::cargo_shim::BuildConfig::build_internal
  10: cargo_web::cargo_shim::BuildConfig::build
  11: cargo_web::build::Project::build
  12: cargo_web::cmd_start::LastBuild::new
  13: cargo_web::cmd_start::command_start
  14: cargo_web::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:305
  17: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  18: std::rt::lang_start_internal
             at libstd/panicking.rs:284
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  19: main
  20: __libc_start_main
  21: _start
```

[edit] more info after some more tests.
Definitely seems to be some issue with today's nightly.
This error occurs on a ubuntu 17.10 virtual machine (run through Virtual Box) and on my host OS (windows 10), just after upgrading to rust version 1.26.0-nightly (259e4a678 2018-03-04).
The error on windows is different :
```
C:\Users\jice\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\bin\lld.exe: error: no output file specified
          C:\Users\jice\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\bin\lld.exe: error: cannot open @C:\Users\jice\AppData\Local\Temp\rustc.zWmi4bmPuK03\linker-arguments: invalid argument
          C:\Users\jice\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\bin\lld.exe: error: no input files
```

**Comment by MaxGraey** [comment]
Same issue

**Comment by koute** [comment]
Thanks for the report!

Fixed.

Please note that to work with newest Rust nightly you also need new `stdweb` which isn't yet released. (But will be very soon.)
